def flush(suits: dict):
    """Returns True if conditions for a four of a kind are met

    Args:
        ranks (dict): dictionary of ranks in a list of cards, generated by Cards.generate_info
    """
    return any(count >= 5 for count in suits.values())