def four_of_a_kind(ranks: dict):
    """Returns True if conditions for a four of a kind are met

    Args:
        ranks (dict): dictionary of ranks in a list of cards, generated by Cards.generate_info
    """
    return any(count >= 4 for count in ranks.values())