def full_house(ranks: dict):
    """Returns True if conditions for a three of a kind are met

    Args:
        ranks (dict): dictionary of ranks in a list of cards, generated by Cards.generate_info
    """
    has_three = any(count == 3 for count in ranks.values())
    has_two = any(count == 2 for count in ranks.values())
    return has_three and has_two