def pair(ranks: dict):
    """Returns True if conditions for a pair are met

    Args:
        ranks (dict): dictionary of ranks in a list of cards, generated by Cards.generate_info
    """
    return any(count == 2 for count in ranks.values())