from .straight_flush import straight_flush

def royal_flush(suits: dict, values: list):
    """Returns True if conditions for a royal flush are met

    Args:
        suits (dict): dictionary of suits from a list of cards, generated by Cards.generate_info
        ranks (list): set of values from a list of cards, generated by Cards.generate_info
    """
    return straight_flush(suits, values) and 14 in values