def straight(values: list):
    """Returns True if conditions for a straight are met

    Args:
        values (list): list of values from a list of cards, reverse ordered, generated by Cards.generate_info
    """
    if len(values) < 5:
        return False
    
    for i in range(len(values) - 4):
        if values[i] - values[i + 4] == 4:
            return True
    return False