def two_pair(ranks: dict):
    """Returns True if conditions for two pair are met

    Args:
        ranks (dict): dictionary of ranks in a list of cards, generated by Cards.generate_info
    """
    pair_count = sum(1 for count in ranks.values() if count >= 2)
    
    return pair_count == 2